# Generated by Django 3.2.5 on 2021-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichepaie', '0002_bullpaie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullpaie',
            name='salaire_brut',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bullpaie',
            name='salaire_net',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bullpaie',
            name='vps',
            field=models.CharField(max_length=255),
        ),
    ]
